name: CD Workflow

on:
  push:
    branches: [ team/react, feature/docker ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        docker build -t bysxx/invader-backend:latest ./backend
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push bysxx/invader-backend:latest
    
    - name: Deploy to Oracle Cloud
      env:
        PRIVATE_KEY: ${{ secrets.ORACLE_CLOUD_PRIVATE_KEY }}
        HOST: ${{ secrets.ORACLE_CLOUD_USER }}@${{ secrets.ORACLE_CLOUD_IP }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        # SSH key 저장 및 권한 설정
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # Docker Hub에서 이미지를 pull하고 실행하는 SSH 명령
        ssh -o StrictHostKeyChecking=no -i private_key.pem $HOST << EOF
          docker pull bysxx/invader-backend:latest
          docker stop invader-backend
          docker rm invader-backend
          docker run -e DB_HOST="${DB_HOST}" DB_NAME="${DB_NAME}" DB_USER="${DB_USER}" DB_PASSWORD="${DB_PASSWORD}" -d --name invader-backend -p 3200:3200 bysxx/invader-backend:latest
        EOF