on:
    push:
      branches:
        - test
  
  jobs:
    test:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  
  
      - name: Set up JDK
        uses: actions/setup-java@v2  
        with:
          distribution: 'adopt'
          java-version: '20.0.2'
  
      - name: Build project
        run: |
          # 컴파일할 Java 파일이 있다면 적절한 경로를 지정해주세요
          find . -name "*.java" > sources.txt
          javac @sources.txt
  
      - name: Update JUnit Platform Console Standalone
        run: |
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar
          mv junit-platform-console-standalone-1.8.2.jar $GITHUB_WORKSPACE/Lib/
  
      - name: Run JUnit tests
        run: |
          java -version
          java -cp $GITHUB_WORKSPACE:$GITHUB_WORKSPACE/Lib/junit-platform-console-standalone-1.8.2.jar org.junit.platform.console.ConsoleLauncher --scan-classpath
  