name: Slack Notification for Main Branch

on:
  pull_request:
    branches: [ main ]

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Send Slack Notification
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "Main 브랜치에 새로운 PR이 있습니다."
        }' ${{ secrets.SLACK_WEBHOOK_URL }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
